//auto-generated file 
var nock = require('nock');
nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/tasks/', {"task":{"command":"test@gopher-express-ngrok.gopher.email","reminder_timeformat":"1sec","reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"bar@bar.email","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1"}}})
  .reply(201, {"status":"success","task":{"id":1535,"trigger_url":"http://local.gopher.email/api/v1/trigger/65a49536a5d1da43d32ae239fd9f8f4e/","created":1516254210,"reminder_time":1516254211,"reminder_timeformat":"1sec","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1","contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},"messages":[]}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:30 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '934',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/tasks/', {"task":{"command":"test@gopher-express-ngrok.gopher.email","reminder_timeformat":"1sec","reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"bar@bar.email","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1"}}})
  .reply(201, {"status":"success","task":{"id":1536,"trigger_url":"http://local.gopher.email/api/v1/trigger/7c01c42cc9cd6e8b4d50d85f9575274b/","created":1516254213,"reminder_time":1516254214,"reminder_timeformat":"1sec","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1","contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},"messages":[]}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:33 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '934',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .get('/api/v1/tasks')
  .query({"%2Flimit":"1"})
  .reply(200, {"status":"success","tasks":[{"id":1071,"trigger_url":"http://local.gopher.email/api/v1/trigger/40ab883c48e2b4ef8b981ff71954b2e4/","created":1515474322,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1072,"trigger_url":"http://local.gopher.email/api/v1/trigger/cae7abccdf4a108371a538eb4b5b9417/","created":1515474340,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1073,"trigger_url":"http://local.gopher.email/api/v1/trigger/3907ab4874f261a852c7ba651e3a641c/","created":1515474366,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1074,"trigger_url":"http://local.gopher.email/api/v1/trigger/d09692ba6455d4bedd8d80dc567da222/","created":1515474490,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1075,"trigger_url":"http://local.gopher.email/api/v1/trigger/d86214a2ba7397458eb2ba5f09e959c8/","created":1515476238,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1076,"trigger_url":"http://local.gopher.email/api/v1/trigger/aa40bcaac903a72f058d74d9c78e562a/","created":1515476737,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1077,"trigger_url":"http://local.gopher.email/api/v1/trigger/4354833870614281785e64a96e98cf89/","created":1515476976,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1078,"trigger_url":"http://local.gopher.email/api/v1/trigger/a3e937ccc4d35958c496d44c895d972b/","created":1515477056,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}}]}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:37 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '6738',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .get('/api/v1/tasks')
  .query({"%2Flimit":"1"})
  .reply(200, {"status":"success","tasks":[{"id":1071,"trigger_url":"http://local.gopher.email/api/v1/trigger/40ab883c48e2b4ef8b981ff71954b2e4/","created":1515474322,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1072,"trigger_url":"http://local.gopher.email/api/v1/trigger/cae7abccdf4a108371a538eb4b5b9417/","created":1515474340,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1073,"trigger_url":"http://local.gopher.email/api/v1/trigger/3907ab4874f261a852c7ba651e3a641c/","created":1515474366,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1074,"trigger_url":"http://local.gopher.email/api/v1/trigger/d09692ba6455d4bedd8d80dc567da222/","created":1515474490,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1075,"trigger_url":"http://local.gopher.email/api/v1/trigger/d86214a2ba7397458eb2ba5f09e959c8/","created":1515476238,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1076,"trigger_url":"http://local.gopher.email/api/v1/trigger/aa40bcaac903a72f058d74d9c78e562a/","created":1515476737,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1077,"trigger_url":"http://local.gopher.email/api/v1/trigger/4354833870614281785e64a96e98cf89/","created":1515476976,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1078,"trigger_url":"http://local.gopher.email/api/v1/trigger/a3e937ccc4d35958c496d44c895d972b/","created":1515477056,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}}]}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:41 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '6738',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .get('/api/v1/tasks')
  .query({"%2Flimit":"1"})
  .reply(200, {"status":"success","tasks":[{"id":1071,"trigger_url":"http://local.gopher.email/api/v1/trigger/40ab883c48e2b4ef8b981ff71954b2e4/","created":1515474322,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1072,"trigger_url":"http://local.gopher.email/api/v1/trigger/cae7abccdf4a108371a538eb4b5b9417/","created":1515474340,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1073,"trigger_url":"http://local.gopher.email/api/v1/trigger/3907ab4874f261a852c7ba651e3a641c/","created":1515474366,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1074,"trigger_url":"http://local.gopher.email/api/v1/trigger/d09692ba6455d4bedd8d80dc567da222/","created":1515474490,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1075,"trigger_url":"http://local.gopher.email/api/v1/trigger/d86214a2ba7397458eb2ba5f09e959c8/","created":1515476238,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":[],"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1076,"trigger_url":"http://local.gopher.email/api/v1/trigger/aa40bcaac903a72f058d74d9c78e562a/","created":1515476737,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1077,"trigger_url":"http://local.gopher.email/api/v1/trigger/4354833870614281785e64a96e98cf89/","created":1515476976,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},{"id":1078,"trigger_url":"http://local.gopher.email/api/v1/trigger/a3e937ccc4d35958c496d44c895d972b/","created":1515477056,"reminder_time":null,"reminder_timeformat":"","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":null,"html":"","text":"","attachments":[]},"private_data":{"contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}}]}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:46 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '6738',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .get('/api/v1/tasks/1535/')
  .reply(200, {"status":"success","task":{"id":1535,"trigger_url":"http://local.gopher.email/api/v1/trigger/65a49536a5d1da43d32ae239fd9f8f4e/","created":1516254210,"reminder_time":1516254211,"reminder_timeformat":"1sec","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1","contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}}}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:50 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '920',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .put('/api/v1/tasks/1535/', {"task":{"reference_email":{"body":"something else new"}}})
  .reply(200, {"status":"success","task":{"id":1535,"trigger_url":"http://local.gopher.email/api/v1/trigger/65a49536a5d1da43d32ae239fd9f8f4e/","created":1516254210,"reminder_time":1516254211,"reminder_timeformat":"1sec","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1","contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},"messages":[]}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:53 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '934',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/extensions/self/data/', {"three":"more"})
  .reply(200, {"data":{"three":"more","evernote_access_token":"abc","more_new_data":"def"},"user":{"name":"Joe Schmoe","email":"esweetland@gmail.com","timezone":"America/Los_Angeles"}}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:56 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '171',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .get('/api/v1/extensions/self/data/')
  .reply(200, {"data":{"three":"more","evernote_access_token":"abc","more_new_data":"def"},"user":{"name":"Joe Schmoe","email":"esweetland@gmail.com","timezone":"America/Los_Angeles"}}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:58 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '171',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .get('/api/v1/natural_time')
  .query({"format":"1day","method":"bcc","timezone":"America%2FLos_Angeles"})
  .reply(200, {"valid":true,"time":"2018-01-18 21:43:59 PST","time_gmt":"2018-01-19 05:43:59","time_ts":"1516340639","recurring":false}, [ 'Date',
  'Thu, 18 Jan 2018 05:43:59 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '121',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/invites/', {"client_id":"ext_be659a394e913e1cd0019053bb6b0e86","email_address":"test@example.com"})
  .reply(200, {"status":"success"}, [ 'Date',
  'Thu, 18 Jan 2018 05:44:00 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '20',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/invites/', {"client_id":"ext_be659a394e913e1cd0019053bb6b0e86","email_address":"test@example.com"})
  .reply(200, {"status":"success"}, [ 'Date',
  'Thu, 18 Jan 2018 05:44:02 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Set-Cookie',
  'PHPSESSID=nsj6h0de8mn164s9kq28k7cbf6; path=/',
  'Expires',
  'Thu, 19 Nov 1981 08:52:00 GMT',
  'Cache-Control',
  'no-store, no-cache, must-revalidate, post-check=0, pre-check=0',
  'Pragma',
  'no-cache',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '20',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/invites/', {"client_id":"ext_be659a394e913e1cd0019053bb6b0e86","email_address":["blackhole@example.com","blackhole2@example.com"]})
  .reply(200, {"status":"success"}, [ 'Date',
  'Thu, 18 Jan 2018 05:44:04 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '20',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/tasks/', {"task":{"command":"test@gopher-express-ngrok.gopher.email","reminder_timeformat":"1sec","reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"bar@bar.email","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1"}}})
  .reply(201, {"status":"success","task":{"id":1537,"trigger_url":"http://local.gopher.email/api/v1/trigger/dc4787e64cbf0339c10f0c10188befbb/","created":1516254262,"reminder_time":1516254263,"reminder_timeformat":"1sec","completed":false,"completed_on":null,"reference_email":{"server_recipient":"test@gopher-express-ngrok.gopher.email","to":["test@gopher-express-ngrok.gopher.email"],"cc":[],"bcc":[],"from":"esweetland@gmail.com","reply_to":"","subject":"Test1","html":"Test1","text":"Test1","attachments":[]},"private_data":{"privatedata1":"Value1","contact_id":"12345"},"relationships":{"user":{"primary_email":"esweetland@gmail.com","emails":["esweetland@gmail.com"],"name":"Joe Schmoe","timezone":"America/Los_Angeles","preferred_date_format":"D, F jS Y g:ia T"},"extension":{"name":"New Gopher Express (Ngrok)","flag":"gopher-express-ngrok","private_data":{"gopher_token":"a875a0a9dd0359479e4f075e65ab3efc3be5ed90"}}}},"messages":[]}, [ 'Date',
  'Thu, 18 Jan 2018 05:44:22 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '934',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/auth/register', {"email":"4068@example.com","password":"fdsafdsa","name":"","timezone":""})
  .reply(200, {"status":"success"}, [ 'Date',
  'Thu, 18 Jan 2018 05:44:27 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '20',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/auth/login', {"email":"4068@example.com","password":"fdsafdsa"})
  .reply(200, {"status":"success","user":{"email":"4068@example.com","token":{"access_token":"1033a4b38769023a4b9ecf039efeac4c014d2d36","expires_in":0,"token_type":"Bearer","scope":"get_user_info extension_manage_self manage_tasks read_tasks read_logs manage_logs read_services manage_extensions read_extensions manage_user_self"}}}, [ 'Date',
  'Thu, 18 Jan 2018 05:44:29 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '318',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);

nock('http://local.gopher.email:80', {"encodedQueryParams":true})
  .post('/api/v1/auth/forgot_password', {"email":"4068@example.com"})
  .reply(200, {"success":true}, [ 'Date',
  'Thu, 18 Jan 2018 05:44:30 GMT',
  'Server',
  'Apache/2.4.10 (Debian)',
  'Cache-Control',
  'no-cache',
  'Access-Control-Allow-Origin',
  '*',
  'Access-Control-Allow-Headers',
  'authorization, Content-Type, cache-control, postman-token',
  'Access-Control-Allow-Methods',
  'GET, POST, PUT ,DELETE, OPTIONS',
  'Content-Length',
  '16',
  'Connection',
  'close',
  'Content-Type',
  'application/json' ]);
